### ISSUE TITLE
Division of vector results results in vecor of size zero

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#80] opened 2015-01-07 18:24 UTC
as illustrated in the test divide_accumulators that references this issue.

**Comment by egull** [comment] 2015-01-07 22:45
had a closer look at this and ended up at the place you were working at earlier, so I think this is related to issue #77

**Comment by galexv** [comment] 2015-01-12 16:35
There is nothing special about division :), multiplication `res1*res2` exhibits the same bug, as well as addition `res1+res1`.  :(  `Result<...>::generate_jackknife()` method is the primary suspect.

**Comment by galexv** [comment] 2015-01-18 14:21
The issue is fixed by commit 5de13ce, closing it...

**Closed by galexv** 2015-01-18 14:21 UTC
Labels: bug, ongoing
