### ISSUE TITLE
Eigen matrices as ALPSCore observables

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#157] opened 2015-09-16 16:53 UTC
As requested by Michele @dolfim and Mauro

**Comment by aeantipov** [comment] 2015-09-17 17:38
Check documentation of `Eigen::Map`. http://eigen.tuxfamily.org/dox/group__TutorialMapClass.html
It allows to use plain contiguous memory storage (`std::vector`) and just interface from and to `Eigen::Matrix`.

**Comment by egull** [comment] 2015-09-17 18:58
Good idea, but it's probably not good enough: for the objects they have in mind you can't just copy things, and it would require them to construct vectors at the beginning and then just use their storage in eigen... not very nice. The only workaround I could imagine is by constructing a custom allocator, but that will get ugly soon.

**Comment by dolfim** [comment] 2015-09-17 19:08
What is exactly the problem? Boost.Serialization for MPI communication? Or are the Eigen Matrices missing some other important concept required for the accumulators?
For the hdf5 serialization I think that having to copy the data is not so bad.

**Comment by aeantipov** [comment] 2015-09-17 19:12
Michele, I think you don't necessarily want to use serialization here. After all Eigen matrices are essentially a contiguous chunk of memory of native MPI datatype that has a set of methods on top for extra functionality. So, serializing here seems a little bit of overkill. 
But I guess the problem is not in mpi, but rather in how to store them in accumulators and calculate statistics/errors.

**Comment by dolfim** [comment] 2015-09-17 19:21
Well, you anyway need to implement the boot serialization method, otherwise you cannot use boost.pi with it. Then yes, it is not much work. I thin it is only a matter of sending shape and contiguous data.

For the statistics I think that most arithmetic operations are implemented. But I see that Jackknife might be more tedious, since there you need element-wise sin(), cos(), etc.

I think that listing all concepts required by a type is a good starting point also for further generalizations.
Here Lukas started the work https://alps.comp-phys.org/trac/wiki/NGSAccumulatorsV2.

**Comment by galexv** [comment] 2015-10-16 02:36
@dolfim :
The development is going on in the branch `devel` (the latest commit is 45b5517c36): accumulators with a "custom type" can be compiled (although method implementations just throw "not implemented" for now), the test file [https://github.com/ALPSCore/ALPSCore/blob/devel/accumulators/test/custom_type.cpp] contains preliminary example of how to introduce a new type and what should be defined. Right now it is rather messy, but we are cleaning it up and will introduce the eigen matrices soon.

**Comment by dolfim** [comment] 2015-10-20 10:11
Thanks a lot. Do you want us to tried it out already in the current stage, or we better wait a bit for the cleaner version?

**Comment by galexv** [comment] 2015-10-20 15:17
The cleaner version is coming (most probably today!), so, it may be better to wait just a little. I am writing better tests and testing.

**Comment by galexv** [comment] 2015-10-23 18:39
It is "almost working", but i am trying to figure out the serialization stuff. Is there more documentation then  at https://alps.comp-phys.org/trac/wiki/NGSHDF5 , i wonder?

**Comment by egull** [comment] 2015-10-23 18:48
I'm not aware of any documentation, no.

**Comment by dolfim** [comment] 2015-10-23 18:49
do you mean understanding the stride, sizes & Co. arguments? Such that you can serialize the contiguous datatype?
The only written documentation is the one you found. The best example is in the alps::numeric::matrix serialization. If you look into it, be aware that lots of the code is legacy conversion from a previous storage type or a fallback for non-contiguous value_type.
If you tell me what you need, I work out other example on Monday.

**Comment by galexv** [comment] 2015-10-23 18:51
I will for now follow the approach used to serialize boost::array in ALPSCore. Should be similar enough.

**Comment by dolfim** [comment] 2015-10-23 18:55
If the question is what do do around line accumulators/test/custom_type.cpp#L373, that is easy:
ar[path+"/value"] << value.value; // for save
ar[path+"/value"] >> value.value; // for load

**Comment by galexv** [comment] 2015-11-16 13:14
Update: Saving/loading custom-type accumulators is actually a bit trickier than it first looked. Among other problems: saving/loading binned accumulators requires saving/loading vectors of the custom type, which, in turn, uses serialization traits (`get_extent`, `get_pointer` etc.) which then must be properly implemented. If we suppress using these traits by declaring the type non-continuous, the MPI broadcast functionality breaks. :)  Still working on it...

**Comment by dolfim** [comment] 2015-11-16 13:31
How does the Boost.MPI Bcast break? I think it is a valid (required) concept that the CustomType is serializable both in terms of ALPS.HDF5 and Boost.MPI.
Writing a Boost.Serialization shouldn't be a huge problem.

**Comment by galexv** [comment] 2015-12-15 03:18
Using custom type as a value type in accumulators/results is now supported; the corresponding sample code is in [accumulators/test/custom_type.hpp](https://github.com/ALPSCore/ALPSCore/blob/aff4f33bd6874bb1923522e7da4ce6e3619fd8a6/accumulators/test/custom_type.hpp). In the sample code methods that are needed to be implemented in a custom value class are marked `@REQUIRED`, `@REQURED_SEQUENCE` and `@REQUIRED_NONCONTINUOUS`.

TODO: Make a working example using specifically Eigen matrix, not a model `custom_type`.
Because of this, i am not closing the issue, but rather pushing it to a "catch all" release for the time being.

**Comment by dolfim** [comment] 2015-12-15 07:55
Thanks a lot. We will give it a try.

**Comment by mwallerb** [comment] 2017-10-18 18:05
Fixed in the ALEA library (commit 5bfd7b61), which uses Eigen by default.

**Closed** 2018-01-11 17:36 UTC
Labels: enhancement
