### ISSUE TITLE
Unexpected behaviour in compiler check

### ISSUE THREAD

**Issue by iskakoff** [ALPSCore/ALPSCore#444] opened 2018-01-31 17:10 UTC
When I have project with specified cmake_minimum_required(VERSION 2.8.12) compiler check failed on Mac:

    ALPSCore C++ compiler ID: AppleClang
    ALPSCore C++ compiler version: 7.0.2.7000181
    Current C++ compiler ID: Clang
    Current C++ compiler version: 7.0.2.7000181
    Current C++ compiler:    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

**Comment by galexv** [comment] 2018-01-31 17:13
Duplicate of #424

**Comment by galexv** [comment] 2018-07-02 14:16
Reason and remedy are described in https://github.com/ALPSCore/ALPSCore/wiki/Known-problems-and-workarounds .

**Closed by galexv** 2018-07-02 14:16 UTC
Labels: duplicate
