### ISSUE TITLE
Zenodo release: Incomplete/incorrect author lists.

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#189] opened 2016-02-07 18:10 UTC
ALPSCore zenodo releases are missing for 0.5.1 and 0.5.2. Alex, Do you know what happened?

**Comment by galexv** [comment] 2016-02-08 14:42
I do see it under my Zenodo login as:

    Alexander Gaenko, Emanuel Gull, Andrey E. Antipov, Lukas Gamper, Gabriele Carcassi, dolfim, Jonas Greitemann, 2015. ALPSCore: Version 0.5.2. doi:10.5281/zenodo.35372

with publicly-accessible DOI  [10.5281/zenodo.35372](http://dx.doi.org/10.5281/zenodo.35372).

The only issue i see is a strange author list (apparently, list of contributors automatically retrieved from GitHub). E.g., it is not immediately clear who is "dolfim" (it must be Michele Dolfi). This needs fixing in the next release, i will change the issue title accordingly.

**Comment by egull** [comment] 2016-02-08 15:22
Here is the search that does not show it:

https://zenodo.org/search?ln=en&p=ALPSCore&action_search=

I wonder why it doesn't show up and if it's a problem on our side...

**Comment by galexv** [comment] 2016-02-08 16:39
I strongly suspect it's a Zenodo's bug. No search returns anything newer than approx. October 26th 2015 (try searching for some frequent word like "of"!). I sent a support request and got this:

    Thank you for your message. Note, due to overwhelming
    interest, we are currently also refurbishing our
    infrastructure. As a result the response times to support
    requests are longer than usual, so please bear with us until
    end-January 2016 when the new infrastructure is scheduled to
    be put in place. Thank you for your understanding and we hope
    you'll find the Zenodo improvements well worth waiting for!

For the record, today is Feb 8th... :-/

**Comment by egull** [comment] 2016-02-15 20:19
Seems that the zenodo search is now fixed. The strange author list persists, of course...

**Comment by aeantipov** [comment] 2016-02-15 20:20
The later is not a bug - Michele didn't type his name on github, so it didn't get parsed. I told him about that.

**Comment by galexv** [comment] 2016-02-15 20:22
Ah, i know it's not a bug of Zenodo: but when uploading, one can fix the author list manually.

**Comment by galexv** [comment] 2016-09-15 17:07
Cf. issue #224 [discussion](https://github.com/ALPSCore/ALPSCore/issues/224#issuecomment-231056298). According to Zenodo:

> Zenodo automatically extracts metadata about your repository from GitHub APIs. The authors are e.g. determined from the repository's contributor statistics. The automatic extraction is solely a best guess. Add a .zenodo.json file the root of your repository to explicit define the metadata. The format of file is the same as for our REST API (use e.g. below JSON to get started).

This can be addressed on our side --- i am re-opening this issue.

**Comment by egull** [comment] 2016-10-09 16:16
OK. Maxent needs a new release too – can you add the maxent version of this json file to the maxent repo and release?

**Comment by galexv** [comment] 2016-10-24 20:11
Just successfully submitted a pre-release to Zenodo (DOI: 10.5281/zenodo.162969); after a few tries the metadata was accepted. Let's see how it will look published.

**Comment by galexv** [comment] 2016-10-24 20:53
I am closing this for now. If any metadata (such as authors or affiliations) needs to be modified, feel free to reopen.

**Closed by galexv** 2016-10-24 20:53 UTC
Labels: enhancement
