### ISSUE TITLE
Possibility of memory leak in alps::params

### ISSUE THREAD

**Issue by ryanlevy** [ALPSCore/ALPSCore#192] opened 2016-02-24 15:45 UTC
After running Maxent through valgrind, there appears to be a small amount of leaked memory from `boost::program_options` within `alps::params`.  ALPSCore was compiled with gcc 4.8.5
See attached valgrind summary
[valgrind_out.txt](https://github.com/ALPSCore/ALPSCore/files/144857/valgrind_out.txt)

**Comment by galexv** [comment] 2016-02-24 16:19
[Just using the issue tracker as my lab notebook :) ]
I have run `alps::params` tests via `valgrind`. So far:

* `mpi_bcast` : leaks detected
* `serialize` : no leaks, but there is unallocated heap on exit

**Comment by galexv** [comment] 2016-02-24 16:35
In `serialize`, the memory is heap-allocated (and never deallocated) somewhere inside HDF5 library called from `alps::hdf5::archive::construct()` (possibly, some HDF5 objects are created and never destroyed?). I think we have seen something like that when running llvm sanitizer, see issue #134.

**Comment by galexv** [comment] 2016-02-24 17:34
In `mpi_bcast`, all leaks and uninitialized memory accesses seems to be inside `OpenMPI` library. This is actually a [known issue](https://www.open-mpi.org/faq/?category=debugging#valgrind_clean) (and the OpenMPI-supplied Valgrind suppression file does not help, either).

The Valgrind leak & error report is practically identical for `mpi_bcast` and for the trivial MPI program:
```C++
#include <mpi.h>

int main(int argc, char** argv)
{
  MPI_Init(&argc,&argv);
  MPI_Finalize();
  return 0;
}
```
from which i conclude that there is no actual memory leak inside `ALPSCore` in `mpi_bcast`.

**Comment by galexv** [comment] 2016-03-29 18:44
Summary: cannot reproduce the issue. 
Ryan: if i can get a code example (preferably minimal example) i will investigate further. So far i am closing the issue --- feel free to reopen!

**Closed by galexv** 2016-03-29 18:44 UTC
Labels: invalid, question
