### ISSUE TITLE
Test fail of serializer_test on jenkins

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#466] opened 2018-02-19 20:01 UTC
Jenkins reports a test failure for build 183:

https://alpscore.ci.cloudbees.com/job/alpscore_fedora17_boost-1.60.0_hdf5-1.8.13_openmpi-1.10.1_quickbuild/changes

the test failure seems to be for the stream_serializer test:
       Start 125: stream_serializer
125/126 Test #125: stream_serializer ........................***Failed    0.01 sec

which fails as:

Error Message

/scratch/jenkins/workspace/alpscore_fedora17_boost-1.60.0_hdf5-1.8.13_openmpi-1.10.1_quickbuild/alea/test/stream_serializer.cpp:145
Value of: out
  Actual:   1.00718
-0.497835 +- 0.00580469
 0.0145448
Expected: in
Which is:   1.00718
-0.497835 +- 0.00580469
 0.0145448

**Comment by krivenko** [comment] 2018-02-19 20:01
https://github.com/ALPSCore/ALPSCore/pull/446#issuecomment-366015295

**Comment by krivenko** [comment] 2018-02-19 20:44
Closing as a duplicate of #462.

**Closed by krivenko** 2018-02-19 20:44 UTC
