### ISSUE TITLE
C++ standard compatibility

### ISSUE THREAD

**Issue by shinaoka** [ALPSCore/ALPSCore#301] opened 2017-03-19 21:44 UTC
Let us imagine the ALPSCore libraries are compiled with C++03 and but one tries to build an application or ALPSCore-extensions with C++11.
It will result in a disaster.
Is it possible to detect such failure when one runs "cmake" for the application? 
Can we set some cmake variable or C++ macros to tell the C++ standard used to build the libraries to applications?

**Comment by aeantipov** [comment] 2017-03-20 01:38
Hiroshi, I am not sure it is a problem. C++11  is not officially supported and extensions are not a part of alpscore (not mature, need more dependencies). I would say it is a user problem. 

There is an option to dump compiler flags and then check the same ones are used. Triqs does it. I don't like this too much. Optimization flags should not necessarily be carried between the lib and the code being linked.
Then also one could just dump a variable with a standard into ALPSCoreConfog.cmake, but it is ad hoc and reduces stability.

Overall I think until alpscore is officially supporting C++11 it is a non-issue. Requiring alpscore being c++11 compiled can be done at the package manager level

**Comment by egull** [comment] 2017-03-20 01:49
How much of this will still be disastrous after we've removed the linking to the boost libraries? Is it the boost components that make this crash or something in ALPS? If it's just boost, we just have to wait for Alex to remove the last few libraries. If it's more general, we should at least put a warning. Same presumably goes for user codes that need C++-11. Hiroshi is not the first one to be tripped up by this...

**Comment by aeantipov** [comment] 2017-03-20 02:19
I think its not tied to boost. Any two codes with c++03 and c++11 std::string won't link.
On Sunday, March 19, 2017 at 21:49 Emanuel Gull <notifications@github.com> wrote:

How much of this will still be disastrous after we've removed the linking to the boost libraries? Is it the boost components that make this crash or something in ALPS? If it's just boost, we just have to wait for Alex to remove the last few libraries. If it's more general, we should at least put a warning. Same presumably goes for user codes that need C++-11. Hiroshi is not the first one to be tripped up by this...

**Comment by galexv** [comment] 2017-03-20 02:20
There are a few issues there.

1. One is that GCC implements `std::string` (and other classes) [differently in different versions](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) of the C++ compiler. Fortunately, the improper mix will not link successfully. Unfortunately, one of the codes (the library or the client) will have to be recompiled with specific options.

2. Another is that a Boost *header* [is compiled differently](http://lists.llvm.org/pipermail/cfe-dev/2014-April/036260.html) by C++11 and C++03 adhering compilers. This is not related with ALPSCore using Boost libraries: using that Boost header causes the problem.  The only solution, as far as i understand, is to make sure that both the library and the client code are compiled by C++ of the same standard.

This is in some sense a generalization of issue #160: make details of ALPSCore compilation available to client libraries.

It is surely possible to advice a client CMake script, via some variable like ALPS_CXX_COMPILER, what compiler (and what options) were used. 

Possiby, something can be verified when client CMake scripts executes ALPSCore CMake package.

Andrey @aeantipov has beaten me by 2 minutes with his comment. :-)

**Comment by galexv** [comment] 2017-03-20 02:28
> Possiby, something can be verified when client CMake scripts executes ALPSCore CMake package.

What i mean is that ALPSCore knows what language standard was used to build it; at the moment of client executing `ALPSCoreConfig.cmake` (via `find_package("ALPSCore")), the compiler and the options that the client uses are also known. The language versions/standards can be compared, and the warning (or outright failure) can be issued.

**Comment by egull** [comment] 2017-03-20 02:43
Here is a solution: check this:
https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD_REQUIRED.html
and this:
https://cmake.org/cmake/help/v3.1/manual/cmake-compile-features.7.html#manual:cmake-compile-features(7)

I propose to enforce c++-98 in ALPSCore, with a flag to switch it to 11 or 14. And to check in the user codes that the standard is the same as the one ALPS has been compiled with. That will barf at configure time if someone tries to mix different standards.

**Comment by shinaoka** [comment] 2017-03-20 03:00
Do we have to raise the requirement of cmake version from cmake 2.8.12 for CXX_STANDARD?

**Comment by galexv** [comment] 2017-03-20 03:07
Yes, we do, to CMake 3.1 (maybe even 3.1.3).

**Comment by egull** [comment] 2017-03-20 03:37
The switch from 3.0 to 3.1 was back in 2015. That's too recent to make it a requirement. Perhaps there is a way to make it optional or leave it undefined/unsafe if the functionality is not available, but I'm hesitant to force 3.1 on the users.

**Comment by jgreitemann** [comment] 2017-03-20 09:06
> I propose to enforce c++-98 in ALPSCore, with a flag to switch it to 11 or 14.

Why introduce ALPSCore-specific CMake options for that? Users on modern (3.1+) CMake releases will be able to switch the standard using the CMake option `-DCMAKE_CXX_STANDARD=98` or `11`. Possibly one could check if CMake supports that feature and make `98` the default. Older versions of CMake don't have a concept of C++ standard so there's no elegant (+portable) way to deal with it. One can always add `-std=c++-98` to `CMAKE_CXX_FLAGS` of course.

Personally, I'd find it confusing if ALPSCore was to override the default behavior of the compiler. Users of, say, GCC 6+ are probably aware their compiler uses C++11 by default and expect this outcome. Checking for compatible standards in `ALPSCoreConfig.cmake` to get a helpful error rather than an obscure linker error would be nice, though.

**Comment by shinaoka** [comment] 2017-03-20 11:39
> Perhaps there is a way to make it optional or leave it undefined/unsafe if the functionality is not available, but I'm hesitant to force 3.1 on the users.
I agree. I do not think we should force 3.1 on the users.
This would make the installation more difficult.

We can dump a flag ALPSCoreConfig.cmake only when they use cmake 3.1 or newer.
If a client application finds an incompatible flag, the user should be warned.

By the way, CMake 3.2.3 seems to be available at the K computer. 
https://docs.google.com/spreadsheets/d/1ykttehDs9vn8XljJ6YE0bwsdjBMjw5sGTjFkVMygjHs/pub?single=true&gid=1&output=html
Todo-san told me that C++11 may come to the K computer this year.

**Comment by shinaoka** [comment] 2017-05-05 01:24
I tested CXX_STANADARD on my mac and found that this option does not affect the behavior clang3.8.
So, I set C++11/14 flags though CMAKE_CXX_FLAGS.
For now, checking this option does not sound very useful because there are multiple ways to set C++11/14 flags.

One related question.
Is it possible to know what compiler (or vender name) was used to build ALPSCore (possibly via CMake)?
In building our impurity solver, I want to "warn" users (including me using several compilers on mac) if compiler mismatch is found.

A native idea may be adding the following in ALPSCore's cmake.
This provides a chance for us to check the vender of the compiler used to build ALPSCore.
And, if they want, they can abort the build of their client application.

set(ALPSCore_CXX_COMPILER_ID @CMAKE_CXX_COMPILER_ID@)
mark_as_advanced(
    ALPSCore_CXX_COMPILER_ID
)

**Comment by galexv** [comment] 2017-12-15 07:58
After some research...

1. I introduced a CMake flag `ALPS_CXX_STD` which can be set to `c++03` or `c++11` (only). The default is currently `c++03`.
2. The flag causes ALPSCore to be built using the corresponding c++ standard setting flags of the compiler. To be more technical, `-DALPS_CXX_STD=c++11` requests `auto` and `constexpr` features that require setting the compiler flags to enable C++11. (The list of features can be expanded later, as needed). This also necessitated to switch to CMake 3.1.
3. This language feature request is transitive: it forces client code to request support of the same features and cause compilation with C++11 when needed.
4. If `c++03` is requested, the CMake script tries to limit the compiler to C++03 too.
5. The user code must be compiled with the same version of the same compiler as ALPSCore; this is now enforced. It may turn out a bit too strict a requirement, but, probably, is the most reliable way to ensure ABI compatibility. 

This, together with using the header-only Boost, should take care of the incompatibilities that we encountered earlier. I can imagine 2 ways to break it:
1. A client code uses ALPSCore compiled with C++03, but is compiled with `-std=c++11` explicitly set (or vice versa). 
In most cases, there will be both options present in compiler invocation; in my experiments, the ALPSCore option had a higher precedence. Alternatively, it may result in an error. 
I believe this situation can be detected in many common cases; if it turns out to be a problem, we can implement this detection.
2.  A client code is compiled explicitly requesting a different version of ABI.
I cannot think of a way to catch this for all cases for all compilers; IMHO, if a user playing with explicit ABI requests, he/she should be knowledgeable enough to recompile ALPSCore using the same ABI.

**Comment by galexv** [comment] 2017-12-15 08:12
One more thought. [In the case of GCC](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html), `std::string` ABI choice is orthogonal to the choice of C++ standard *within the same version of the compiler* (which we now enforce). The Boost problems we saw earlier were caused by Boost having being compiled with an older version of compiler with the "old" ABI; this is now taken care by using header-only Boost. Therefore, we do not actually need to enforce C++03 for the client code even if ALPSCore is compiled with C++03. This would take care of a [concern expressed earlier](https://github.com/ALPSCore/ALPSCore/issues/301#issuecomment-287705733).

The 2nd problem mentioned in [the earlier comment](https://github.com/ALPSCore/ALPSCore/issues/301#issuecomment-287667671) still stands, but seems to be reported for Clang on Mac only. We can enforce C++03 on client (or warn the client) only if Clang+Mac combination is detected. And anyway we are dropping C++03.

**Comment by shinaoka** [comment] 2017-12-15 10:55
Do you mean that the ALPSCore and client code can be compiled with different C++ standards if the both are linked to the same C++ std library?

It'd be nice to have c++14 for ALPS_CXX_STD.

**Comment by kleinhenz** [comment] 2017-12-15 19:39
Does it make sense to provide c++03 as an option (especially as a default) now that a lot of new c++11 only code is being introduced? Do we intend to actively support c++03 with a bunch of ifdefs going forward? I'm not sure that this is worth it if almost half of the library (gf and alea) won't be usable in c++03 mode. Legacy c++03 codes should probably just depend on a legacy version of ALPSCore.

**Comment by galexv** [comment] 2017-12-15 19:41
@kleinhenz Once we merge c++11 branch in, the support for c++03 will be removed.

**Comment by shinaoka** [comment] 2017-12-18 22:05
I am now testing this new feature for my some project using c++14 (gcc5.4).
The client code must be compiled with c++14 (to be consistent with TRIQS libraries).
The new feature enforces the client code to be compiled with c++11 (when ALPSCore is built with c++11).
This causes problems.

Let me update my wish list (or my to-do list?)

- c++14 support for ALPS_CXX_STD
- It is better to be able to set the c++ standard flag (like -std=c++11) manually as an option.

**Comment by galexv** [comment] 2017-12-18 22:15
@shinaoka Thanks for the "wishlist", I am working on this.

**Comment by galexv** [comment] 2017-12-22 17:33
@shianoka If CMake version >= 3.1, the "right" way to do is to call `target_compile_features()` on the relevant targets with appropriate feature list. For example, `target_compile_features(my_library PUBLIC "cxx_decltype_auto")` requests that target `my_library` uses `decltype(auto)` language feature and that any dependent targets should use it too (hence, `PUBLIC`). This feature implies C++14, and CMake will automatically choose appropriate options depending on the compiler (and on the CMake version, because later versions know more about newer compilers). The feature lists seem to be combined with those of dependencies, so if ALPSCore wanted only C++11 features, the project will still be compiled with C++14 options. This should not be a problem, because as of now i am not aware about any ABI interoperability problems between C++11 and C++14 (C++03 is an exception).

Nevertheless, i am figuring out how it can be done if the client code insists of explicitly specifying "-std=c++14" in the compiler flags.

**Comment by galexv** [comment] 2017-12-23 06:13
ALPSCore can be build with `-DALPS_CXX_STD` set to `c++03`, `c++11`, `c++14` and `custom`.

Setting `-DALPS_CXX_STD=custom` will prevent requesting any compiler features; the C++ standard will be set by compiler flags only, and a client code C++ standard will have to be set manually.

Client may define, before `find_package(ALPSCore)`:

1) `set(ALPS_FORCE_CXX_STD ${std})`
                to request standard `${std}` when compiling targets that depend on ALPSCore;

`${std}` can be:
"C++11"  --- requests C++11
"C++14"  --- requests C++14
"custom" --- does not request anything; the compiler is governed only by user-set compiler flags.

2) `set(ALPS_FORCE_NO_COMPILER_CHECK true)`  to ignore detected mismatch between ALPSCore's and the client's compilers.

I hope this addresses Hiroshi(@shinaoka)'s requirements.

**Comment by shinaoka** [comment] 2017-12-24 10:08
Thank you for your work!
That seems to address my requirements.
I will test the new code with the CT-HYB code.

**Comment by shinaoka** [comment] 2018-01-08 05:24
This new functionality works well for the CT-HYB code.
Shall we close this issue?

**Comment by galexv** [comment] 2018-01-08 15:02
Thanks for testing it! Closing.

**Closed by galexv** 2018-01-08 15:02 UTC
Labels: enhancement, fix issued
