### ISSUE TITLE
RealVectorObservable reduce crash

### ISSUE THREAD

**Issue by egull** [ALPSCore/ALPSCore#198] opened 2016-03-20 18:34 UTC
I'm getting something very similar to bug #46: 

terminate called after throwing an instance of 'std::logic_error'
  what():  No alps::mpi::reduce available for this type St6vectorIS_IdSaIdEESaIS1_EE
In /global/homes/g/gull/ALPSCore/install/include/alps/accumulators/mpi.hpp on 197 in reduce_impl

could it be that somehow this bug came back?

Intel spits it out, mainly after aggressive optimization...

**Comment by egull** [comment] 2016-03-20 18:37
quick  note: root crashes on line 222, slaves crash on line 197

**Comment by egull** [comment] 2016-03-20 18:45
...and the demangler says that we're trying to reduce this:

std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >

...so a vector of vectors of double. Should we be allowed to do that?

**Comment by egull** [comment] 2016-03-20 18:52
problem seems to come from trying to reduce a MeanAccumulator<std::vector<double> >. For other data types this seems to work flawlessly.

**Comment by egull** [comment] 2016-03-20 19:45
same seems to happen with NoBinning accumulators, but the LogBinning ones work nicely.

**Comment by galexv** [comment] 2016-03-22 13:34
I cannot reproduce it on Cori with our existing tests. Emanuel (@egull), could you please attach a small example?

**Comment by galexv** [comment] 2016-03-22 17:23
Testing on flux with Intel v.15.0
Intel's `-fast` is evil: it implies `-static` which messes up the build (see #199).
Intel's `-ipo` is evil: the compilation fails with unresolved externals which ought to be defined in GoogleTest.

**Comment by galexv** [comment] 2016-03-22 18:30
Seems like `-ipo` strips symbols from the resulting object files. Compare:

Without `-ipo`:

```sh
$ echo 'extern "C" int foo(int x) { return x; }' >test.cxx
$ icpc -O3 -c -o test.o test.cxx
$ nm test.o
                 U __gxx_personality_v0
0000000000000000 T foo

$ nm test.o | grep foo; echo $?
0000000000000000 T foo
0
```

With `-ipo`:

```sh
$ echo 'extern "C" int foo(int x) { return x; }' >test.cxx
$ icpc -O3 -ipo -c -o test.o test.cxx
$ nm test.o
$ nm test.o | grep foo; echo $?
1
```

**Comment by terletska** [comment] 2016-03-25 17:02
Alex, Hanna just reproduced this intermittently on comet in her code. It's a different ctaux code, but it shows the same problem.

**Comment by galexv** [comment] 2016-03-25 20:30
Hanna (@terletska): is it the code that i was helping to install a couple of days ago?

**Comment by terletska** [comment] 2016-03-25 20:33
yes.

**Comment by terletska** [comment] 2016-03-25 22:21
here is example of output

I keep getting it for other runs

**Comment by galexv** [comment] 2016-03-28 15:59
It seems to be independent of optimization options and/or compiler. I reproduced it on my laptop with g++: it crashes when collecting measurements with different number of data points (Emanuel (@egull)  — thanks a lot for the idea!)

**Comment by galexv** [comment] 2016-03-28 23:35
AFAICU, the problem boils down to the fact that `alps::hdf5:: is_vectorizable(vvec)` returns `false` if `vvec` is a vector containing vectors of different sizes.

**Comment by galexv** [comment] 2016-03-31 15:46
Hanna says her code is running fine now, so i am closing the issue.
Emanuel, if your code still crashes, please reopen this one or start a new issue!

**Closed by galexv** 2016-03-31 15:46 UTC
Labels: bug
